//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bakkal
{
    using System;
    using System.Collections.Generic;
    
    public partial class sepetTb
    {
        public int sepetID { get; set; }
        public string sepetBarkod { get; set; }
        public string sepetAd { get; set; }
        public string sepetFiyat { get; set; }
        public string sepetStok { get; set; }
    }
}
