//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bakkal
{
    using System;
    using System.Collections.Generic;
    
    public partial class urunTablosu
    {
        public int urunID { get; set; }
        public string urunBarkod { get; set; }
        public string urunAd { get; set; }
        public string urunFiyat { get; set; }
        public string urunStok { get; set; }
    }
}
